class TestsError(ValueError):
    """Tests exception."""
    pass
